package openwrt

import (
	"context"
	"encoding/binary"
	"fmt"
	"math/bits"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/Alaxay8/routeflux/internal/domain"
)

const defaultFirewallRulesPath = "/tmp/routeflux-firewall.nft"

const (
	udpTProxyMark     = "0x1"
	udpTProxyMarkMask = "0x1"
	udpTProxyTable    = "100"
	udpTProxyPriority = "1000"
)

var allLANSourceCIDRs = []string{
	"10.0.0.0/8",
	"172.16.0.0/12",
	"192.168.0.0/16",
}

var bypassDestinationCIDRs = []string{
	"0.0.0.0/8",
	"10.0.0.0/8",
	"100.64.0.0/10",
	"127.0.0.0/8",
	"169.254.0.0/16",
	"172.16.0.0/12",
	"192.168.0.0/16",
	"224.0.0.0/4",
	"240.0.0.0/4",
}

// FirewallRulesPath returns the nftables include generated by RouteFlux.
func FirewallRulesPath() string {
	if path := os.Getenv("ROUTEFLUX_FIREWALL_RULES"); path != "" {
		return path
	}
	return defaultFirewallRulesPath
}

// FirewallManager applies transient nftables rules for transparent proxy routing.
type FirewallManager struct {
	NFTPath            string
	IPPath             string
	RulesPath          string
	DNSMasqPath        string
	DNSMasqServicePath string
	DNSMasqSnippetPath string
	ProcRoot           string
}

// NewFirewallManager creates an OpenWrt nftables-based firewall manager.
func NewFirewallManager() FirewallManager {
	return FirewallManager{
		NFTPath:            "/usr/sbin/nft",
		IPPath:             "/sbin/ip",
		RulesPath:          FirewallRulesPath(),
		DNSMasqPath:        dnsmasqBinaryPath(),
		DNSMasqServicePath: dnsmasqServicePath(),
		DNSMasqSnippetPath: dnsmasqSnippetOverridePath(),
		ProcRoot:           "/proc",
	}
}

// Validate ensures the current platform supports the requested firewall mode.
func (m FirewallManager) Validate(ctx context.Context, settings domain.FirewallSettings) error {
	if domain.NormalizeFirewallTargetMode(settings.TargetMode) == domain.FirewallTargetModeBypass {
		return nil
	}
	expandedDomains := domain.ExpandFirewallTargetDomains(settings.TargetServiceCatalog, settings.TargetServices, settings.TargetDomains)
	if len(expandedDomains) == 0 {
		return nil
	}
	if err := m.ensureDNSMasqNFTSetSupport(ctx); err != nil {
		return err
	}
	if _, err := m.dnsmasqSnippetPath(); err != nil {
		return err
	}
	return nil
}

// Apply renders and loads nftables rules.
func (m FirewallManager) Apply(ctx context.Context, settings domain.FirewallSettings) error {
	if err := m.Validate(ctx, settings); err != nil {
		return err
	}

	rules, err := BuildNFTablesRules(settings)
	if err != nil {
		return err
	}
	if err := atomicWriteText(m.RulesPath, rules, 0o644); err != nil {
		return fmt.Errorf("write firewall rules: %w", err)
	}

	m.cleanupPolicyRouting(ctx)
	_ = m.run(ctx, "delete", "table", "inet", "routeflux")
	if err := m.run(ctx, "-f", m.RulesPath); err != nil {
		return fmt.Errorf("apply nftables rules: %w", err)
	}
	if needsUDPPolicyRouting(settings) {
		if err := m.setupPolicyRouting(ctx); err != nil {
			_ = m.run(ctx, "delete", "table", "inet", "routeflux")
			m.cleanupPolicyRouting(ctx)
			return err
		}
	}

	targetMode := domain.NormalizeFirewallTargetMode(settings.TargetMode)
	catalog := settings.TargetServiceCatalog
	services := settings.TargetServices
	domains := settings.TargetDomains
	if targetMode == domain.FirewallTargetModeBypass {
		catalog = nil
		services = nil
		domains = nil
	}

	if err := m.syncDNSMasqTargets(ctx, catalog, services, domains); err != nil {
		return fmt.Errorf("sync dnsmasq targets: %w", err)
	}

	return nil
}

// Disable removes the transient RouteFlux nftables table.
func (m FirewallManager) Disable(ctx context.Context) error {
	m.cleanupPolicyRouting(ctx)
	err := m.run(ctx, "delete", "table", "inet", "routeflux")
	if err != nil && !strings.Contains(strings.ToLower(err.Error()), "no such file or directory") {
		return err
	}
	_ = os.Remove(m.RulesPath)
	if err := m.syncDNSMasqTargets(ctx, nil, nil, nil); err != nil {
		return err
	}
	return nil
}

// BuildNFTablesRules returns an nftables ruleset for the provided targets.
func BuildNFTablesRules(settings domain.FirewallSettings) (string, error) {
	targetCIDRs := domain.ExpandFirewallTargetCIDRs(settings.TargetServiceCatalog, settings.TargetServices, settings.TargetCIDRs)
	targetDomains := domain.ExpandFirewallTargetDomains(settings.TargetServiceCatalog, settings.TargetServices, settings.TargetDomains)
	targets, err := normalizeFirewallTargets(targetCIDRs)
	if err != nil {
		return "", err
	}
	sources, err := normalizeFirewallSources(settings.SourceCIDRs)
	if err != nil {
		return "", err
	}
	targetMode := len(targets) > 0 || len(targetDomains) > 0
	targetBypassMode := domain.NormalizeFirewallTargetMode(settings.TargetMode) == domain.FirewallTargetModeBypass
	if !targetMode && len(sources) == 0 {
		return "", fmt.Errorf("at least one target service/domain/IP/CIDR or one source host is required")
	}

	redirectSources := sources
	if targetMode {
		redirectSources, err = normalizeFirewallTargets(allLANSourceCIDRs)
		if err != nil {
			return "", err
		}
	}

	port := settings.TransparentPort
	if port <= 0 {
		port = 12345
	}

	var builder strings.Builder
	builder.WriteString("table inet routeflux {\n")
	if targetMode && !targetBypassMode {
		builder.WriteString("  set target_v4 {\n    type ipv4_addr\n    flags interval\n")
		if len(targets) > 0 {
			fmt.Fprintf(&builder, "    elements = { %s }\n", strings.Join(targets, ", "))
		}
		builder.WriteString("  }\n\n")
	}
	if len(redirectSources) > 0 {
		fmt.Fprintf(&builder, "  set source_v4 {\n    type ipv4_addr\n    flags interval\n    elements = { %s }\n  }\n\n", strings.Join(redirectSources, ", "))
		fmt.Fprintf(&builder, "  set bypass_v4 {\n    type ipv4_addr\n    flags interval\n    elements = { %s }\n  }\n\n", strings.Join(bypassDestinationCIDRs, ", "))
	}

	builder.WriteString("  chain prerouting {\n    type nat hook prerouting priority dstnat; policy accept;\n")
	if len(redirectSources) > 0 {
		builder.WriteString("    ip daddr @bypass_v4 return\n")
		fmt.Fprintf(&builder, "    ip saddr @source_v4 tcp dport != %d redirect to :%d\n", port, port)
	}
	builder.WriteString("  }\n")

	if len(redirectSources) > 0 {
		builder.WriteString("\n  chain prerouting_mangle {\n    type filter hook prerouting priority mangle; policy accept;\n")
		builder.WriteString("    ip daddr @bypass_v4 return\n")
		fmt.Fprintf(&builder, "    ip saddr @source_v4 udp dport 443 meta mark set %s tproxy ip to :%d accept\n", udpTProxyMark, port)
		builder.WriteString("  }\n")
	}

	if targetMode && !targetBypassMode {
		fmt.Fprintf(&builder, "\n  chain output {\n    type nat hook output priority -100; policy accept;\n    ip daddr @target_v4 tcp dport != %d redirect to :%d\n  }\n", port, port)
	}

	builder.WriteString("}\n")
	return builder.String(), nil
}

func normalizeFirewallTargets(targets []string) ([]string, error) {
	seen := make(map[string]struct{}, len(targets))
	out := make([]string, 0, len(targets))
	for _, target := range targets {
		target = strings.TrimSpace(target)
		if target == "" {
			continue
		}

		normalized, err := normalizeFirewallTarget(target)
		if err != nil {
			return nil, err
		}
		for _, item := range normalized {
			if _, ok := seen[item]; ok {
				continue
			}
			seen[item] = struct{}{}
			out = append(out, item)
		}
	}

	sort.Strings(out)
	return out, nil
}

func normalizeFirewallSources(sources []string) ([]string, error) {
	for _, source := range sources {
		if isAllFirewallSource(source) {
			return normalizeFirewallTargets(allLANSourceCIDRs)
		}
	}
	return normalizeFirewallTargets(sources)
}

func normalizeFirewallTarget(target string) ([]string, error) {
	switch {
	case parseIPv4(target), parseIPv4CIDR(target):
		return []string{target}, nil
	case strings.Contains(target, "-"):
		cidrs, err := expandIPv4Range(target)
		if err != nil {
			return nil, err
		}
		return cidrs, nil
	default:
		return nil, fmt.Errorf("unsupported target %q: only IPv4, IPv4 CIDR, and IPv4 ranges are supported", target)
	}
}

func isAllFirewallSource(value string) bool {
	value = strings.TrimSpace(value)
	return strings.EqualFold(value, "all") || value == "*"
}

func parseIPv4(value string) bool {
	ip := net.ParseIP(value)
	return ip != nil && ip.To4() != nil
}

func parseIPv4CIDR(value string) bool {
	ip, _, err := net.ParseCIDR(value)
	return err == nil && ip.To4() != nil
}

func expandIPv4Range(value string) ([]string, error) {
	parts := strings.SplitN(value, "-", 2)
	if len(parts) != 2 {
		return nil, fmt.Errorf("invalid IPv4 range %q", value)
	}

	startIP := net.ParseIP(strings.TrimSpace(parts[0]))
	endIP := net.ParseIP(strings.TrimSpace(parts[1]))
	if startIP == nil || startIP.To4() == nil || endIP == nil || endIP.To4() == nil {
		return nil, fmt.Errorf("unsupported target %q: only IPv4, IPv4 CIDR, and IPv4 ranges are supported", value)
	}

	start := ipv4ToUint32(startIP)
	end := ipv4ToUint32(endIP)
	if start > end {
		return nil, fmt.Errorf("invalid IPv4 range %q: start must be <= end", value)
	}

	return ipv4RangeToCIDRs(start, end), nil
}

func ipv4RangeToCIDRs(start, end uint32) []string {
	var cidrs []string
	for start <= end {
		prefix := 32 - bits.TrailingZeros32(start)
		remaining := end - start + 1
		maxBlockPrefix := 32 - (bits.Len32(remaining) - 1)
		if prefix < maxBlockPrefix {
			prefix = maxBlockPrefix
		}

		cidrs = append(cidrs, fmt.Sprintf("%s/%d", uint32ToIPv4(start).String(), prefix))
		if prefix == 0 {
			break
		}
		step := uint64(1) << (32 - prefix)
		start = uint32(uint64(start) + step)
	}
	return cidrs
}

func ipv4ToUint32(ip net.IP) uint32 {
	return binary.BigEndian.Uint32(ip.To4())
}

func uint32ToIPv4(value uint32) net.IP {
	buf := make([]byte, 4)
	binary.BigEndian.PutUint32(buf, value)
	return net.IP(buf)
}

func (m FirewallManager) run(ctx context.Context, args ...string) error {
	cmd := exec.CommandContext(ctx, m.NFTPath, args...)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("%s %s: %w: %s", m.NFTPath, strings.Join(args, " "), err, strings.TrimSpace(string(output)))
	}
	return nil
}

func (m FirewallManager) runIP(ctx context.Context, args ...string) error {
	cmd := exec.CommandContext(ctx, m.IPPath, args...)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("%s %s: %w: %s", m.IPPath, strings.Join(args, " "), err, strings.TrimSpace(string(output)))
	}
	return nil
}

func (m FirewallManager) setupPolicyRouting(ctx context.Context) error {
	if err := m.runIP(ctx, "route", "add", "local", "0.0.0.0/0", "dev", "lo", "table", udpTProxyTable); err != nil {
		return fmt.Errorf("configure udp tproxy route: %w", err)
	}
	if err := m.runIP(ctx, "rule", "add", "fwmark", udpTProxyMark+"/"+udpTProxyMarkMask, "table", udpTProxyTable, "priority", udpTProxyPriority); err != nil {
		_ = m.runIP(ctx, "route", "del", "local", "0.0.0.0/0", "dev", "lo", "table", udpTProxyTable)
		return fmt.Errorf("configure udp tproxy rule: %w", err)
	}
	return nil
}

func (m FirewallManager) cleanupPolicyRouting(ctx context.Context) {
	_ = m.runIP(ctx, "rule", "del", "fwmark", udpTProxyMark+"/"+udpTProxyMarkMask, "table", udpTProxyTable, "priority", udpTProxyPriority)
	_ = m.runIP(ctx, "route", "del", "local", "0.0.0.0/0", "dev", "lo", "table", udpTProxyTable)
}

func needsUDPPolicyRouting(settings domain.FirewallSettings) bool {
	if !settings.Enabled {
		return false
	}

	targetCIDRs := domain.ExpandFirewallTargetCIDRs(settings.TargetServiceCatalog, settings.TargetServices, settings.TargetCIDRs)
	targetDomains := domain.ExpandFirewallTargetDomains(settings.TargetServiceCatalog, settings.TargetServices, settings.TargetDomains)
	if len(targetCIDRs) > 0 || len(targetDomains) > 0 {
		return true
	}

	sources, err := normalizeFirewallSources(settings.SourceCIDRs)
	return err == nil && len(sources) > 0
}

func atomicWriteText(path, data string, perm os.FileMode) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}

	tmp, err := os.CreateTemp(filepath.Dir(path), filepath.Base(path)+".tmp-*")
	if err != nil {
		return err
	}
	tmpPath := tmp.Name()
	defer func() { _ = os.Remove(tmpPath) }()

	if _, err := tmp.WriteString(data); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Chmod(perm); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Sync(); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}

	return os.Rename(tmpPath, path)
}
