package openwrt

import (
	"context"
	"encoding/binary"
	"fmt"
	"math/bits"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/Alaxay8/routeflux/internal/domain"
)

const defaultFirewallRulesPath = "/tmp/routeflux-firewall.nft"

var allLANSourceCIDRs = []string{
	"10.0.0.0/8",
	"172.16.0.0/12",
	"192.168.0.0/16",
}

// FirewallRulesPath returns the nftables include generated by RouteFlux.
func FirewallRulesPath() string {
	if path := os.Getenv("ROUTEFLUX_FIREWALL_RULES"); path != "" {
		return path
	}
	return defaultFirewallRulesPath
}

// FirewallManager applies transient nftables rules for transparent proxy routing.
type FirewallManager struct {
	NFTPath   string
	RulesPath string
}

// NewFirewallManager creates an OpenWrt nftables-based firewall manager.
func NewFirewallManager() FirewallManager {
	return FirewallManager{
		NFTPath:   "/usr/sbin/nft",
		RulesPath: FirewallRulesPath(),
	}
}

// Apply renders and loads nftables rules.
func (m FirewallManager) Apply(ctx context.Context, settings domain.FirewallSettings) error {
	rules, err := BuildNFTablesRules(settings)
	if err != nil {
		return err
	}
	if err := atomicWriteText(m.RulesPath, rules, 0o644); err != nil {
		return fmt.Errorf("write firewall rules: %w", err)
	}

	_ = m.run(ctx, "delete", "table", "inet", "routeflux")
	if err := m.run(ctx, "-f", m.RulesPath); err != nil {
		return fmt.Errorf("apply nftables rules: %w", err)
	}

	return nil
}

// Disable removes the transient RouteFlux nftables table.
func (m FirewallManager) Disable(ctx context.Context) error {
	err := m.run(ctx, "delete", "table", "inet", "routeflux")
	if err != nil && !strings.Contains(strings.ToLower(err.Error()), "no such file or directory") {
		return err
	}
	_ = os.Remove(m.RulesPath)
	return nil
}

// BuildNFTablesRules returns an nftables ruleset for the provided targets.
func BuildNFTablesRules(settings domain.FirewallSettings) (string, error) {
	targets, err := normalizeFirewallTargets(settings.TargetCIDRs)
	if err != nil {
		return "", err
	}
	sources, err := normalizeFirewallSources(settings.SourceCIDRs)
	if err != nil {
		return "", err
	}
	if len(targets) == 0 && len(sources) == 0 {
		return "", fmt.Errorf("at least one target IP/CIDR or one source host is required")
	}

	port := settings.TransparentPort
	if port <= 0 {
		port = 12345
	}

	var builder strings.Builder
	builder.WriteString("table inet routeflux {\n")
	if len(targets) > 0 {
		fmt.Fprintf(&builder, "  set target_v4 {\n    type ipv4_addr\n    flags interval\n    elements = { %s }\n  }\n\n", strings.Join(targets, ", "))
	}
	if len(sources) > 0 {
		fmt.Fprintf(&builder, "  set source_v4 {\n    type ipv4_addr\n    flags interval\n    elements = { %s }\n  }\n\n", strings.Join(sources, ", "))
	}

	builder.WriteString("  chain prerouting {\n    type nat hook prerouting priority dstnat; policy accept;\n")
	if len(targets) > 0 {
		fmt.Fprintf(&builder, "    ip daddr @target_v4 tcp dport != %d redirect to :%d\n", port, port)
	}
	if len(sources) > 0 {
		fmt.Fprintf(&builder, "    ip saddr @source_v4 tcp dport != %d redirect to :%d\n", port, port)
		if settings.BlockQUIC {
			builder.WriteString("    ip saddr @source_v4 udp dport 443 drop\n")
		}
	}
	builder.WriteString("  }\n")

	if len(targets) > 0 {
		fmt.Fprintf(&builder, "\n  chain output {\n    type nat hook output priority -100; policy accept;\n    ip daddr @target_v4 tcp dport != %d redirect to :%d\n  }\n", port, port)
	}

	builder.WriteString("}\n")
	return builder.String(), nil
}

func normalizeFirewallTargets(targets []string) ([]string, error) {
	seen := make(map[string]struct{}, len(targets))
	out := make([]string, 0, len(targets))
	for _, target := range targets {
		target = strings.TrimSpace(target)
		if target == "" {
			continue
		}

		normalized, err := normalizeFirewallTarget(target)
		if err != nil {
			return nil, err
		}
		for _, item := range normalized {
			if _, ok := seen[item]; ok {
				continue
			}
			seen[item] = struct{}{}
			out = append(out, item)
		}
	}

	sort.Strings(out)
	return out, nil
}

func normalizeFirewallSources(sources []string) ([]string, error) {
	for _, source := range sources {
		if isAllFirewallSource(source) {
			return normalizeFirewallTargets(allLANSourceCIDRs)
		}
	}
	return normalizeFirewallTargets(sources)
}

func normalizeFirewallTarget(target string) ([]string, error) {
	switch {
	case parseIPv4(target), parseIPv4CIDR(target):
		return []string{target}, nil
	case strings.Contains(target, "-"):
		cidrs, err := expandIPv4Range(target)
		if err != nil {
			return nil, err
		}
		return cidrs, nil
	default:
		return nil, fmt.Errorf("unsupported target %q: only IPv4, IPv4 CIDR, and IPv4 ranges are supported", target)
	}
}

func isAllFirewallSource(value string) bool {
	value = strings.TrimSpace(value)
	return strings.EqualFold(value, "all") || value == "*"
}

func parseIPv4(value string) bool {
	ip := net.ParseIP(value)
	return ip != nil && ip.To4() != nil
}

func parseIPv4CIDR(value string) bool {
	ip, _, err := net.ParseCIDR(value)
	return err == nil && ip.To4() != nil
}

func expandIPv4Range(value string) ([]string, error) {
	parts := strings.SplitN(value, "-", 2)
	if len(parts) != 2 {
		return nil, fmt.Errorf("invalid IPv4 range %q", value)
	}

	startIP := net.ParseIP(strings.TrimSpace(parts[0]))
	endIP := net.ParseIP(strings.TrimSpace(parts[1]))
	if startIP == nil || startIP.To4() == nil || endIP == nil || endIP.To4() == nil {
		return nil, fmt.Errorf("unsupported target %q: only IPv4, IPv4 CIDR, and IPv4 ranges are supported", value)
	}

	start := ipv4ToUint32(startIP)
	end := ipv4ToUint32(endIP)
	if start > end {
		return nil, fmt.Errorf("invalid IPv4 range %q: start must be <= end", value)
	}

	return ipv4RangeToCIDRs(start, end), nil
}

func ipv4RangeToCIDRs(start, end uint32) []string {
	var cidrs []string
	for start <= end {
		prefix := 32 - bits.TrailingZeros32(start)
		remaining := end - start + 1
		maxBlockPrefix := 32 - (bits.Len32(remaining) - 1)
		if prefix < maxBlockPrefix {
			prefix = maxBlockPrefix
		}

		cidrs = append(cidrs, fmt.Sprintf("%s/%d", uint32ToIPv4(start).String(), prefix))
		if prefix == 0 {
			break
		}
		step := uint64(1) << (32 - prefix)
		start = uint32(uint64(start) + step)
	}
	return cidrs
}

func ipv4ToUint32(ip net.IP) uint32 {
	return binary.BigEndian.Uint32(ip.To4())
}

func uint32ToIPv4(value uint32) net.IP {
	buf := make([]byte, 4)
	binary.BigEndian.PutUint32(buf, value)
	return net.IP(buf)
}

func (m FirewallManager) run(ctx context.Context, args ...string) error {
	cmd := exec.CommandContext(ctx, m.NFTPath, args...)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("%s %s: %w: %s", m.NFTPath, strings.Join(args, " "), err, strings.TrimSpace(string(output)))
	}
	return nil
}

func atomicWriteText(path, data string, perm os.FileMode) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}

	tmp, err := os.CreateTemp(filepath.Dir(path), filepath.Base(path)+".tmp-*")
	if err != nil {
		return err
	}
	tmpPath := tmp.Name()
	defer func() { _ = os.Remove(tmpPath) }()

	if _, err := tmp.WriteString(data); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Chmod(perm); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Sync(); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}

	return os.Rename(tmpPath, path)
}
